### ISSUE TITLE
Release the Yedit-class on pypi

### ISSUE THREAD

**Issue by luto** [kwoodson/ansible-role-yedit#24]
As there doesn't seem to be any other module to edit yml files safely: Could you please publish the `Yedit` backend class as an independent module on pypi?

**Comment by yfried** [comment]
Great module. could you please contribute it to core ansible?

**Comment by kwoodson** [comment]
@yfried, sorry for the long wait on this.  I'll look into this.

Thanks!

**Comment by ssbarnea** [comment]
I am working an preparing this module to be become a core ansible module. I do not see any need for publishing it on pypi as this would not make it available to ansible.

I will close this but feel free to comment, if we find a good reason to make it a python module, I do not mind.
