### ISSUE TITLE
Incompatible with CentOS 6

### ISSUE THREAD

**Issue by juliusliunz** [kwoodson/ansible-role-yedit#40]
CentOS 6 uses Python 2.6, which requires the position of format field to be explicitly specified. Otherwise the module will fail with the error message:
`
File \"/tmp/ansible_jeh8mY/ansible_module_yedit.py\", line 215, in Yedit\r\n    backup_ext=\".{}\".format(time.strftime(\"%Y%m%dT%H%M%S\")),\r\nValueError: zero length field name in format\r\n", "msg": "MODULE FAILURE", "rc": 1`

**Comment by kwoodson** [comment]
@juliusliunz, I have cleaned up yedit in order to open my PR against ansible core.  It included these changes you mentioned in your PR.

Can you test the latest?  If we still need updates we can get your changes in to work with CentOS 6.

Thanks

**Comment by tdmalone** [comment]
@kwoodson Ok I tried some monkey patching of my local copy of the role - it looks like these two changes are missing:

https://github.com/kwoodson/ansible-role-yedit/pull/41/files#diff-1247c9a5559be75581ce8356c0e51c58L204 (lines 204 & 205)

After patching those, I'm able to run this on a CentOS6 server with Python 2.6.6, without the `zero length field name in format` error.
