### ISSUE TITLE
how to use seprator

### ISSUE THREAD

**Issue by thatsk** [kwoodson/ansible-role-yedit#71]
---
- hosts: localhost
  gather_facts: false
  roles:
    - yedit
  tasks:
  - name:  editing files
    yedit:
      src: '/tmp/versions.yaml'
      edits:
        - key: "war-1.0-dev"
          value: "1.15.0-2019061723.23313320"

Desire file should be like this:-
war-1.0-dev : 1.15.0-2019061723.23313320

but it showing 
war-1
  0-dev: 1.15.0-2019061723.23313320

**Comment by tdmalone** [comment]
`separator` is set to `.` by default, so it's splitting at the `.` halfway through your key. Try setting it to something like `#` (or another value that you know won't ever exist in your keys).

eg.
```yaml
yedit:
  src: '/tmp/versions.yaml'
  separator: "#"
```

**Comment by thatsk** [comment]
thank you so much @tdmalone
