### ISSUE TITLE
swap out PyYaml in favor of ruamel.yaml

### ISSUE THREAD

**Issue by luto** [kwoodson/ansible-role-yedit#8]
Based on [a bunch of the comments on stackoverflow](http://stackoverflow.com/questions/20805418/pyyaml-dump-format/36760452#36760452) our current library, PyYaml, is not being currently worked on.

[PyYaml](http://pyyaml.org/) only supports yaml 1.1 which came out in 2004. The [relevant issue](http://pyyaml.org/ticket/139) was last touched two years ago.
[Ruamel.yaml](http://yaml.readthedocs.io/en/latest/) also supports yaml 1.2 which is more recent, 2009.  In addition, it enables us to preserve comments and formatting.

**Comment by kwoodson** [comment]
@luto,
:+1: for this.  The problem is requiring people having ruamel.yaml.

**Comment by kwoodson** [comment]
@luto, as it stands today we can fallback to pyyaml but we attempt to use ruamel if available.  We've found that this works in most cases.

**Comment by brutus** [comment]
Seems _PyYaml_ is not quiet dead yet — it has slowly become active again over the last months. That said, I think using _ruamel_ if available and fall back to _PyYaml_ is a reasonable approach.

And as far as I see, that's what the code does right now, or not?

If the library will be packaged though (https://github.com/kwoodson/yedit/issues/24), you might want to choose one for `install_requires` as default and put the other in `extras_require` for your `setup.py` (or something similar).

**Comment by kwoodson** [comment]
@brutus, 
>  I think using ruamel if available and fall back to PyYaml is a reasonable approach.

That was the intention and requirement when working where ruamel wasn't available.

> If the library will be packaged though (#24), you might want to choose one for install_requires as default and put the other in extras_require for your setup.py (or something similar).

I asked for help from @ashcrow at looking at packaging.  He went through the process in #29.  My only issue there is some users have asked about using this module through galaxy.  If we package for python then I'm not sure this is available for those users who want to install with galaxy.  Since this isn't my use case I'm unfamiliar with it.

**Comment by ssbarnea** [comment]
Next week we will see a new release of pyyaml and the project was resurected.

Current code supports both ruamel and pyyaml which makes this ticket not needed anymore. If we can use any of them, i do not see the need to do any swap.
